dist: trusty

sudo: required

addons:
  postgresql: "10"

language: go

os:
    - linux

go:
  - 1.8
  - 1.9
  - "1.10"
  - tip

matrix:
  allow_failures:
  - go: tip

env:
   - PREST_PG_USER=postgres PREST_PG_DATABASE=prest PREST_PG_PORT=5432 PREST_CONF=$TRAVIS_BUILD_DIR/testdata/prest.toml

before_script:
    - sh testdata/schema.sh

script:
    - sh testdata/migrations_test.sh
    - go test -race ./...

deploy:
    - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
        tags: true
        condition: $TRAVIS_OS_NAME = linux

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/b7314cbdd840e64940fb
